### ISSUE TITLE
Deploy-to-Bluemix button fails to start

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/natural-language-understanding-nodejs#1]
Due to a credentials issue:

```
2017-03-06T09:35:38.47-0500 [APP/0]      ERR Error: Argument error: username and password are required unless use_unauthenticated is set
2017-03-06T09:35:38.47-0500 [APP/0]      ERR     at NaturalLanguageUnderstandingV1.BaseService (/home/vcap/app/node_modules/watson-developer-cloud/lib/base_service.js:45:18)
2017-03-06T09:35:38.47-0500 [APP/0]      ERR     at Object.<anonymous> (/home/vcap/app/app.js:20:13)
2017-03-06T09:35:38.47-0500 [APP/0]      ERR     at Module._compile (module.js:570:32)
2017-03-06T09:35:38.47-0500 [APP/0]      ERR     at Object.Module._extensions..js (module.js:579:10)
2017-03-06T09:35:38.47-0500 [APP/0]      ERR     at Function.Module._load (module.js:438:3)
```

Which is due to the NLU service not being [declared in the manifest](https://github.com/watson-developer-cloud/natural-language-understanding-nodejs/blob/master/manifest.yml).

**Comment by nfriedly** [comment]
The logs now say

`Binding service my-nlu-service to app natural-language-understanding-nodejs-nfriedly-943 in org nfriedly@us.ibm.com / space dev as nfriedly@us.ibm.com...
OK`

But, it's still failing with the same issue :/

**Comment by nfriedly** [comment]
Second issue is that unlike literally *all* other Watson services, NLU uses dashes instead of underscores in VCAP_SERVICES. Fix to the Node.js SDK incomming...

**Comment by germanattanasio** [comment]
Let me take a look
