### ISSUE TITLE
Semantic roles parsing breaks on ++

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/natural-language-understanding-nodejs#2]
As in the sample sentence: "I like the programming language c++."

Errors with:

```
bundle.js:5784 Uncaught SyntaxError: Invalid regular expression: /\bthe programming language c++\b/: Nothing to repeat
    at new RegExp (<anonymous>)
    at https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5784:2571
    at Array.reduce (native)
    at t.value (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5784:2279)
    at t.value (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5784:2848)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5231:8347)
    at ReactCompositeComponentWrapper._renderValidatedComponent (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5231:8503)
    at ReactCompositeComponentWrapper.performInitialMount (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5231:3971)
    at ReactCompositeComponentWrapper.mountComponent (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5231:3017)
    at Object.mountComponent (https://natural-language-understanding-demo.mybluemix.net/scripts/bundle.js:5342:271)
```

**Comment by jtpollard** [comment]
Also affected by brackets () within the text to be analysed.
