### ISSUE TITLE
react Dependency not found on dependencies in package.json

### ISSUE THREAD

**Issue by mmhinz** [watson-developer-cloud/natural-language-understanding-nodejs#25]
bx app push
...
   2018-04-21T23:26:19.05-0300 [APP/PROC/WEB/0] OUT > node server.js
   2018-04-21T23:26:20.05-0300 [APP/PROC/WEB/0] ERR module.js:478
   2018-04-21T23:26:20.05-0300 [APP/PROC/WEB/0] ERR     throw err;
   2018-04-21T23:26:20.05-0300 [APP/PROC/WEB/0] ERR     ^
   2018-04-21T23:26:20.05-0300 [APP/PROC/WEB/0] ERR Error: Cannot find module 'react'
   2018-04-21T23:26:20.05-0300 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (module.js:476:15)
...
AND
...
   2018-04-22T00:03:58.98-0300 [APP/PROC/WEB/0] ERR 				^
   2018-04-22T00:03:58.98-0300 [APP/PROC/WEB/0] ERR Error: Cannot find module 'html-to-react' from '/home/vcap/app/views'
   2018-04-22T00:03:58.98-0300 [APP/PROC/WEB/0] ERR     at /home/vcap/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
...

1) add react": "^15.6.2 and "html-to-react": "^1.3.3" in package.json at dependencies section.

**Comment by germanattanasio** [comment]
Make sure you install the dependencies using `npm`.

1. Navigate to the folder where the `package.json` file is.
1. Open a terminal and run
    ```
    npm install
    ```

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
